export const projects = [
  // {
  //   title: "MERN Memories",
  //   description:
  //     "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
  //   image: "/images/1.png",
  //   tags: ["Mongo", "Express", "React", "Node"],
  //   source: "https://google.com",
  //   visit: "https://google.com",
  //   id: 0,
  // },
  {
    title: "Next E-commerce",
    description:
      "E-Commerce Website with payment functionality.",
    image: "/images/next-ecommerce.png",
    tags: ["NextJS", "ReactJS", "Stripe", "Tailwilnd CSS"],
    source: "https://github.com/Akram898/next-shop",
    visit: "https://next-shop-wheat.vercel.app/",
    id: 10,
  },
  {
    title: "Ai Article Summarizer",
    description:
      "Sumarizeing your Articles with OpenAI API",
    image: "/images/ai-article-summarizer.png",
    tags: ["NextJS", "ReactJS", "Stripe", "Tailwilnd CSS"],
    source: "https://github.com/Akram898/ai-summarize",
    visit: "https://ai-article-summarizer-1.netlify.app/",
    id: 11,
  },
  {
    title: "Amazon Clone",
    description:
      "E-Commerce Website with payment functionality and User authentication.",
    image: "/images/amazon-clone.PNG",
    tags: ["React", "Next JS", "Tailwilnd CSS"],
    source: "https://github.com/Akram898/new-amazon-clone",
    visit: "https://new-amazon-clone.vercel.app/",
    id: 0,
  },
  {
    title: "Food To Go",
    description: "Food Ordering Platform.",
    image: "/images/elakl.png",
    tags: ["HTML", "SASS", "BootStrap", "JS", "Firebase"],
    source: "https://github.com/Akram898/",
    visit: "https://foodtogo-e1546.web.app/",
    id: 1,
  },
  // {
  //   title: "WebRTC App",
  //   description:
  //     "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
  //   image: "/images/3.jpg",
  //   tags: ["React", "WebRTC"],
  //   source: "https://google.com",
  //   visit: "https://google.com",
  //   id: 2,
  // },
  {
    title: "Movies App",
    description:
      "Movies and series Web Application shows the new movies and shows and search functionality",
    image: "/images/movies.PNG",
    tags: ["React", "Sass", "Material UI", "JS"],
    source: "https://github.com/Akram898/react-movies-app",
    visit: "https://react-movies-tv.netlify.app/",
    id: 2,
  },
  {
    title: "Motortoys Store",
    description: "Online Store for Motor Marine & Powersports",
    image: "/images/Capture-2.JPG",
    tags: ["HTML", "Css", "BootStrap", "JS"],
    source: "https://github.com/Akram898/",
    visit: "http://gibbons-marine-new.simplywebeditor.com/",
    id: 3,
  },

  // {
  //   title: "Breaking Bad App",
  //   description: "Show the cast of Breaking Bad using API",
  //   image: "/images/br.PNG",
  //   tags: ["React", "Css", "JS"],
  //   source: "https://github.com/Akram898/react-breaking-bad-show",
  //   visit: "https://react-breaking-bad-show.netlify.app/",
  //   id: 4,
  // },
  {
    title: "Relax App",
    description: "Relxation App",
    image: "/images/relaxer.JPG",
    tags: ["HTML", "CSS", "JS"],
    source: "https://github.com/Akram898/relaxer",
    visit: "https://relaxer-app2.netlify.app/",
    id: 5,
  },
  {
    title: "Tesla Clone",
    description: "Tesla Website Clone",
    image: "/images/tesla.png",
    tags: ["React JS", "Next JS", "SASS"],
    source: "https://github.com/Akram898/tesla-clone",
    visit: "https://tesla-clone-22.netlify.app/",
    id: 6,
  },
  {
    title: "Book The Chefs",
    description: "A food ordering platform with displaying and adding chefs",
    image: "/images/bookthechef-- - Copy.PNG",
    tags: ["HTLML", "SASS", "JavaScript"],
    source: "https://github.com/Akram898/bookTheChef",
    visit: "https://bookthechefs-10cb0.web.app/",
    id: 7,
  },
  {
    title: "Yalla Parking Clone",
    description: "Find Parking space around Dubai",
    image: "/images/yalla2.PNG",
    tags: ["HTML", "CSS", "Google Maps API", "Javascript"],
    source: "https://github.com/Akram898/",
    visit: "https://dashop-7af56.firebaseapp.com/",
    id: 8,
  },
  {
    title: "Be Happy",
    description: "A Motivation Website",
    image: "/images/behappy-Capture.PNG",
    tags: ["Wordpress", "HTML", "PHP"],
    source: "https://github.com/Akram898/",
    visit: "https://freshstart-b7ac4.web.app/",
    id: 8,
  },
  {
    title: "Tech World",
    description: "Digital Agency Website",
    image: "/images/Capture.PNG",
    tags: ["HTML", "CSS", "Bootsrtap", "Javascript"],
    source: "https://github.com/Akram898/New-Site",
    visit: "https://akram898.github.io/New-Site/",
    id: 9,
  },
  // {
  //   title: "Task Reminder",
  //   description: "Task Reminder App",
  //   image: "/images/task-manager.PNG",
  //   tags: ["React JS", "CSS", "JavaScript"],
  //   source: "https://github.com/Akram898/react-task-tracker",
  //   visit: "https://react-task-tracker-2.netlify.app/",
  //   id: 10,
  // },
];

export const TimeLineData = [
  { year: 2017, text: "Started my journey" },
  { year: 2018, text: "Worked as a freelance developer" },
  { year: 2019, text: "Founded JavaScript Mastery" },
  { year: 2020, text: "Shared my projects with the world" },
  { year: 2021, text: "Started my own platform" },
];
